# Generated by Django 3.1.5 on 2021-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='a',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
