# Generated by Django 3.1.5 on 2021-01-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='a',
        ),
        migrations.RemoveField(
            model_name='room',
            name='a',
        ),
    ]
