# Generated by Django 3.1.5 on 2021-01-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210119_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_room', to='api.room'),
        ),
    ]
