# Generated by Django 3.1.5 on 2021-01-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210126_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
