# Generated by Django 3.1.5 on 2021-02-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_players_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='api.user'),
            preserve_default=False,
        ),
    ]
