# Generated by Django 3.1.5 on 2021-02-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_room_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='leader',
        ),
    ]
