# Generated by Django 3.1.5 on 2021-02-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_easyword_hardword_mediumword_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timer',
            field=models.BooleanField(default=False),
        ),
    ]
