# Generated by Django 3.1.5 on 2021-02-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_room_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='easy',
        ),
        migrations.RemoveField(
            model_name='words',
            name='hard',
        ),
        migrations.RemoveField(
            model_name='words',
            name='medium',
        ),
        migrations.AddField(
            model_name='words',
            name='guess',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='words',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_words', to='api.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
