# Generated by Django 3.1.5 on 2021-02-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210203_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='easyword',
            name='img',
            field=models.CharField(default='https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg', max_length=150),
        ),
        migrations.AddField(
            model_name='hardword',
            name='img',
            field=models.CharField(default='https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg', max_length=150),
        ),
        migrations.AddField(
            model_name='mediumword',
            name='img',
            field=models.CharField(default='https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg', max_length=150),
        ),
        migrations.AddField(
            model_name='words',
            name='img',
            field=models.CharField(default='https://pixabay.com/get/g4b09d9e0d046b094964dc9977fdc17ef984ffc0a09a6b0f4947ab5bff0448dfe1e40a4a4c3fed4d594931b0d4c5d0f5b2b17e7561f3f44e90845bc30eca2df21_640.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='easyword',
            name='word',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hardword',
            name='word',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='mediumword',
            name='word',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
