# Generated by Django 3.1.5 on 2021-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210204_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='words_amount',
            field=models.IntegerField(default=20),
        ),
    ]
