# Generated by Django 3.1.5 on 2021-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210204_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='finish_time',
            field=models.IntegerField(default=60),
        ),
    ]
